name: Run mytvsuper
on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时运行
  workflow_dispatch:
      
permissions:
  contents: write

jobs:
  run_mytvsuper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # 可以根据你的 Python 版本进行修改
      
      - name: Install dependencies
        run: pip install  requests simplejson # 如果有依赖可以在这里安装
      
      - name: Run mytvsuper.py
        env:
         MYTVSUPER_API_TOKEN: ${{ secrets.MYTVSUPER_API_TOKEN }}
        run: python mytvsuper.py
      
      - name: Save generated file to GitHub
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          
          git add mytvsuper.m3u
          
          # 防止文件没变化时出错
          if git diff --cached --quiet; then
            echo "No changes detected, creating empty commit."
            git commit --allow-empty -m "Update mytvsuper.m3u"
          else
            git commit -m "Update mytvsuper.m3u"
          fi
          
          git push -f
